# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#


title: SEAR
sear_version: 0.3.1
description: >- # this means to ignore newlines until "baseurl:"
  A standardized JSON interface for RACF
permalink: /:title/ 

favicon_ico: /assets/images/favicon.png

# Build settings
remote_theme: just-the-docs/just-the-docs@v0.10.1
include:
  - contribute.markdown
color_scheme: sear

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search.heading_level: 3
# Maximum amount of previews per search result
# Default: 3
search.previews: 5

# Maximum amount of words to display before a matched word in the preview
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
search.preview_words_after: 10
search.tokenizer_separator: /[\s/]+/

search.rel_url: false

search.button: true

# Aux links for the upper right navigation
aux_links:
  "View/Contribute on GitHub":
    - "https://github.com/Mainframe-Renewal-Project/sear"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: True

# Use for Warning and Note block quote sections.
callouts:
  warning:
    title: ‚ö†Ô∏è Warning
    color: yellow
  note:
    title: üí° Note
    color: blue
  experimental:
    title: üöß Experimental
    color: red
  development_status:
    title: üöß Development Status
    color: red

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "11.12.1"

# Set the right markdown style
markdown: kramdown
kramdown:
  parse_block_html: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
